// Code generated by protoc-gen-grpc-gateway
// source: segstore.proto
// DO NOT EDIT!

/*
Package segstore is a reverse proxy.

It translates gRPC into RESTful JSON APIs.
*/
package segstore

import (
	"io"
	"net/http"

	"github.com/golang/protobuf/proto"
	"github.com/grpc-ecosystem/grpc-gateway/runtime"
	"github.com/grpc-ecosystem/grpc-gateway/utilities"
	"golang.org/x/net/context"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/grpclog"
)

var _ codes.Code
var _ io.Reader
var _ = runtime.String
var _ = utilities.NewDoubleArray

// RegisterSegStoreHandlerFromEndpoint is same as RegisterSegStoreHandler but
// automatically dials to "endpoint" and closes the connection when "ctx" gets done.
func RegisterSegStoreHandlerFromEndpoint(ctx context.Context, mux *runtime.ServeMux, endpoint string, opts []grpc.DialOption) (err error) {
	conn, err := grpc.Dial(endpoint, opts...)
	if err != nil {
		return err
	}
	defer func() {
		if err != nil {
			if cerr := conn.Close(); cerr != nil {
				grpclog.Printf("Failed to close conn to %s: %v", endpoint, cerr)
			}
			return
		}
		go func() {
			<-ctx.Done()
			if cerr := conn.Close(); cerr != nil {
				grpclog.Printf("Failed to close conn to %s: %v", endpoint, cerr)
			}
		}()
	}()

	return RegisterSegStoreHandler(ctx, mux, conn)
}

// RegisterSegStoreHandler registers the http handlers for service SegStore to "mux".
// The handlers forward requests to the grpc endpoint over "conn".
func RegisterSegStoreHandler(ctx context.Context, mux *runtime.ServeMux, conn *grpc.ClientConn) error {
	client := NewSegStoreClient(conn)

	return nil
}

var ()

var ()
